### ISSUE TITLE
Highlighting then dragging tokens can cause them to disappear on Firefox 

### ISSUE THREAD

**Issue by michaelferrara** [ucfopen/syntax-sorter-materia-widget#20]
On Firefox, if you highlight multiple elements including the tokens, then drag a token, sometimes a token will disappear. Usually if the token is in the starting box after being highlighted, then dragged and dropped back into the starting box, it will disappear. Also, usually if the token is in the starting box after being highlighted, then dragged and dropped onto the answer line, the token on the right of it will disappear.

**Comment by clpetersonucf** [comment]
Resolved via #30, included in v1.1.0
